apps/engineering/urls.py
from django.urls import path, include
from rest_framework.routers import DefaultRouter

from apps.engineering import views

router = DefaultRouter()
router.register(r'projects', views.ProjectViewSet)
router.register(r'create/project', views.CreateProjectViewSet)
router.register(r'projectstage', views.ProjectStageViewSet)
router.register(r'files', views.ProjectFileViewSet)
router.register(r'create/file', views.CreateProjectFileViewSet)
router.register(r'equipments', views.ProjectEquipmentViewSet)
router.register(r'create/equipment', views.CreateProjectEquipmentViewSet)
router.register(r'budgets', views.ProjectBudgetViewSet)
router.register(r'create/budget', views.CreateProjectBudgetViewSet)
router.register(r'bids', views.ProjectBidViewSet)
router.register(r'create/bid', views.CreateProjectBidViewSet)
router.register(r'quotes', views.ProjectQuoteViewSet)
router.register(r'create/quote', views.CreateProjectQuoteViewSet)
router.register(r'quoteitems', views.ProjectQuoteItemViewSet)
router.register(r'create/quoteitem', views.CreateProjectQuoteItemViewSet)
router.register(r'designs', views.ProjectDesignViewSet)
router.register(r'create/design', views.CreateProjectDesignViewSet)
router.register(r'fabrications', views.ProjectFabricationViewSet)
router.register(r'create/fabrication', views.CreateProjectFabricationViewSet)

urlpatterns = [
    path('engineering/directory/', views.ProjectsView.as_view(), name='projects_directory'),
    path('engineering/project/<slug>/overview/', views.ProjectView.as_view(), name='project_overview'),
    path('engineering/project/<slug>/documents/', views.ProjectFilesView.as_view(), name='project_documents'),
    path('engineering/project/<slug>/documents/<file_slug>/delete/', views.ProjectFileDeleteView.as_view(),
         name='project_document_delete'),
    path('engineering/project/<slug>/designs/', views.ProjectDesignsView.as_view(), name='project_designs'),
    path('engineering/project/<slug>/designs/<file_slug>/delete/', views.ProjectDesignDeleteView.as_view(),
         name='project_design_delete'),
    path('engineering/project/<slug>/equipments/', views.ProjectEquipmentsView.as_view(), name='project_equipments'),
    path('engineering/project/<slug>/equipments/<file_slug>/delete/', views.ProjectEquipmentDeleteView.as_view(),
         name='project_equipment_delete'),
    path('engineering/project/<slug>/equipments/<equipment_slug>/edit/', views.ProjectEquipmentView.as_view(),
         name='project_equipment_edit'),
    path('engineering/project/<slug>/bidding/', views.ProjectBiddingView.as_view(), name='project_bidding'),
    path('engineering/project/<slug>/bidding/status/', views.ProjectBiddingEditView.as_view(),
         name='project_bidding_status'),
    path('engineering/project/<slug>/bidding/status/<bid_slug>/<bid_action>/', views.ProjectBidStatusView.as_view(),
         name='project_bid_status'),
    path('engineering/project/<slug>/quotation/', views.ProjectQuotationView.as_view(), name='project_quotation'),
    path('engineering/project/<slug>/quotation/new/<quote_item_slug>/', views.ProjectQuotationItemNewView.as_view(),
         name='project_quotation_edit'),
    path('engineering/project/<slug>/quotation/status/<quote_item_slug>/<quote_item_action>/',
         views.ProjectQuotationItemStatusView.as_view(),
         name='project_quotation_status'),
    path('engineering/project/<slug>/fabrication/', views.ProjectFabricationView.as_view(), name='project_fabrication'),
    path('engineering/project/<slug>/fabrication/<task_slug>/clear/', views.ProjectFabricationClearView.as_view(),
         name='project_fabrication_clear'),
    path('engineering/project/<slug>/fabrication/status/<fabrication_slug>/<fabrication_action>/',
         views.ProjectFabricationStatusView.as_view(),
         name='project_fabrication_status'),

    path('api/v1/engineering/forms/leads/', views.ProjectLeadsViewSet.as_view()),
    path('api/v1/engineering/forms/teams/', views.ProjectTeamViewSet.as_view()),
    path('api/v1/engineering/forms/equipments/', views.ProjectEquipmentsViewSet.as_view()),
    path('api/v1/engineering/forms/projects/', views.ProjectFormViewSet.as_view()),
    path('api/v1/engineering/', include(router.urls)),
]

noandgerp/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView

from noandgerp import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('apps.general.urls')),
    path('', include('apps.users.urls')),
    path('', include('apps.engineering.urls')),
    path('', include('apps.logistics.urls')),
    path('', include('apps.compliance.urls')),
    # path('', include('apps.warehouse.urls')),
    # path('', include('apps.construction.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
# handler404 = TemplateView.as_view(template_name='index.html')

apps/engineering/models.py
from django.contrib.auth.models import User
from django.db import models
from simple_history.models import HistoricalRecords

from configs import random_code, BID_STATUS, QUOTE_STATUS, DESIGN_TYPE, FABRICATION_STATUS


class Project(models.Model):
    name = models.CharField(max_length=255, unique=True)
    lead = models.ForeignKey(User, on_delete=models.SET(1))
    description = models.TextField()
    owner_name = models.CharField(max_length=255, null=True, blank=True)
    owner_email = models.EmailField(max_length=55, null=True, blank=True)
    bidding = models.BooleanField(default=False, blank=True)
    logistics_bidding = models.BooleanField(default=False, blank=True)
    members = models.ManyToManyField(User, related_name='project_member', blank=True)
    commissioned = models.BooleanField(default=False)
    slug = models.SlugField(null=True, db_index=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    history = HistoricalRecords()

    @property
    def _history_user(self):
        return self.changed_by

    @_history_user.setter
    def _history_user(self, value):
        self.changed_by = value

    class Meta:
        ordering = ['name']

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = random_code()
        super().save(*args, **kwargs)

    def __str__(self):
        return self.name


class ProjectStage(models.Model):
    project = models.ForeignKey(Project, on_delete=models.CASCADE)
    name = models.CharField(max_length=255, unique=True)
    stage_status = models.BooleanField(default=False)
    stage_percentage = models.CharField(max_length=20)
    slug = models.SlugField(null=True, db_index=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['created_at']

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = random_code()
        super().save(*args, **kwargs)

    def __str__(self):
        return self.project.name


class ProjectFile(models.Model):
    project = models.ForeignKey(Project, on_delete=models.CASCADE)
    name = models.CharField(max_length=255)
    description = models.TextField()
    document = models.FileField(upload_to='documents')
    slug = models.SlugField(null=True, db_index=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['name']

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = random_code()
        super().save(*args, **kwargs)

    def __str__(self):
        return self.name


class ProjectDesign(models.Model):
    project = models.ForeignKey(Project, on_delete=models.CASCADE)
    name = models.CharField(max_length=255)
    description = models.TextField()
    document = models.FileField(upload_to='designs')
    design_type = models.CharField(max_length=68, choices=DESIGN_TYPE, blank=False, default='FEED')
    slug = models.SlugField(null=True, db_index=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['name']

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = random_code()
        super().save(*args, **kwargs)

    def __str__(self):
        return self.name


class ProjectEquipment(models.Model):
    project = models.ForeignKey(Project, on_delete=models.CASCADE)
    name = models.CharField(max_length=255)
    unit_cost = models.FloatField()
    unit_cost_in = models.CharField(max_length=55)
    length = models.FloatField()
    width = models.FloatField()
    height = models.FloatField()
    measurement_in = models.CharField(max_length=55)
    weight = models.FloatField()
    weight_in = models.CharField(max_length=55)
    estimated_quantity = models.FloatField()
    description = models.TextField()
    slug = models.SlugField(null=True, db_index=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['name']

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = random_code()
        super().save(*args, **kwargs)

    def __str__(self):
        return self.name


class ProjectBudget(models.Model):
    project = models.ForeignKey(Project, on_delete=models.CASCADE)
    name = models.CharField(max_length=255)
    unit_cost = models.FloatField()
    unit_cost_in = models.CharField(max_length=55)
    description = models.TextField()
    slug = models.SlugField(null=True, db_index=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['name']

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = random_code()
        super().save(*args, **kwargs)

    def __str__(self):
        return self.name


class ProjectBid(models.Model):
    project = models.ForeignKey(Project, on_delete=models.CASCADE)
    vendor = models.ForeignKey(User, on_delete=models.CASCADE)
    bid_status = models.CharField(max_length=68, choices=BID_STATUS, blank=False, default='Open')
    slug = models.SlugField(null=True, db_index=True, blank=True)
    rfq = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['created_at']

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = random_code()
        super().save(*args, **kwargs)

    def __str__(self):
        return f'{self.vendor.first_name} {self.vendor.last_name}'


class ProjectQuote(models.Model):
    project = models.ForeignKey(Project, on_delete=models.CASCADE)
    slug = models.SlugField(null=True, db_index=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['created_at']

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = random_code()
        super().save(*args, **kwargs)

    def __str__(self):
        return f'{self.project.name}'


class ProjectQuoteItem(models.Model):
    project = models.ForeignKey(Project, on_delete=models.CASCADE)
    quote = models.ForeignKey(ProjectQuote, on_delete=models.CASCADE)
    vendor = models.ForeignKey(User, on_delete=models.CASCADE)
    equipment = models.ForeignKey(ProjectEquipment, on_delete=models.CASCADE)
    quote_status = models.CharField(max_length=68, choices=QUOTE_STATUS, blank=False, default='Open')
    quote_price = models.FloatField(default=0)
    slug = models.SlugField(null=True, db_index=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['quote_price']

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = random_code()
        super().save(*args, **kwargs)

    def __str__(self):
        return f'{self.equipment.name}'


class ProjectFabrication(models.Model):
    title = models.CharField(max_length=255)
    project = models.ForeignKey(Project, on_delete=models.CASCADE)
    team = models.ForeignKey(User, on_delete=models.CASCADE)
    description = models.TextField()
    fabrication_status = models.CharField(max_length=68, choices=FABRICATION_STATUS, blank=False, default='Ongoing')
    due_date = models.DateField()
    slug = models.SlugField(null=True, db_index=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['created_at']

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = random_code()
        super().save(*args, **kwargs)

    def __str__(self):
        return f'{self.title}'

apps/engineering/forms.py
from django import forms

from apps.engineering.models import Project, ProjectFile, ProjectDesign, ProjectEquipment, ProjectQuoteItem, \
    ProjectFabrication


class ProjectForm(forms.ModelForm):
    class Meta:
        model = Project
        exclude = ('owner_name', 'owner_email', 'bidding', 'logistics_bidding', 'members', 'commissioned', 'slug')

    def __init__(self, *args, **kwargs):
        super(ProjectForm, self).__init__(*args, **kwargs)
        for visible in self.visible_fields():
            visible.field.widget.attrs['class'] = 'form-control'


class ProjectFileForm(forms.ModelForm):
    class Meta:
        model = ProjectFile
        exclude = ('project', 'slug')

    def __init__(self, *args, **kwargs):
        super(ProjectFileForm, self).__init__(*args, **kwargs)
        for visible in self.visible_fields():
            visible.field.widget.attrs['class'] = 'form-control'


class ProjectDesignForm(forms.ModelForm):
    class Meta:
        model = ProjectDesign
        exclude = ('project', 'slug')

    def __init__(self, *args, **kwargs):
        super(ProjectDesignForm, self).__init__(*args, **kwargs)
        for visible in self.visible_fields():
            visible.field.widget.attrs['class'] = 'form-control'


class ProjectEquipmentForm(forms.ModelForm):
    class Meta:
        model = ProjectEquipment
        exclude = ('project', 'slug')

    def __init__(self, *args, **kwargs):
        super(ProjectEquipmentForm, self).__init__(*args, **kwargs)
        for visible in self.visible_fields():
            visible.field.widget.attrs['class'] = 'form-control'


class ProjectQuoteItemForm(forms.ModelForm):
    class Meta:
        model = ProjectQuoteItem
        exclude = ('project', 'quote', 'vendor', 'equipment', 'quote_status', 'quote_price', 'slug')

    def __init__(self, *args, **kwargs):
        super(ProjectQuoteItemForm, self).__init__(*args, **kwargs)
        for visible in self.visible_fields():
            visible.field.widget.attrs['class'] = 'form-control'


class ProjectFabricationForm(forms.ModelForm):
    due_date = forms.DateField(widget=forms.TextInput(attrs={'id': 'flatpickr01', 'data-toggle': 'flatpickr'}))

    class Meta:
        model = ProjectFabrication
        exclude = ('project', 'slug')

    def __init__(self, *args, **kwargs):
        super(ProjectFabricationForm, self).__init__(*args, **kwargs)
        for visible in self.visible_fields():
            visible.field.widget.attrs['class'] = 'form-control'

templates/engineering/index.html
{% extends 'index.html' %}
{% load static %}

{% block css %}

{% endblock %}


{% block content %}

    <!-- .page -->
    <div class="page">
        <!-- .page-inner -->
        <div class="page-inner">
            <!-- .page-title-bar -->
            <header class="page-title-bar">

                <!-- title and toolbar -->
                <div class="d-md-flex align-items-md-start">
                    <h1 class="page-title mr-sm-auto"> Engineering </h1><!-- .btn-toolbar -->
                    <div class="btn-toolbar">
                        {% if perms.engineering.add_project %}
                            <button type="button" class="btn btn-light" data-toggle="modal"
                                    data-target="#newProject">
                                <i class="oi oi-plus"></i>
                                <span class="ml-1">New Project</span>
                            </button>

                            <!-- Modal Drawer Right -->
                            <div class="modal fade" id="newProject" tabindex="-1" role="dialog"
                                 aria-labelledby="newProjectLabel" aria-hidden="true">
                                <!-- .modal-dialog -->
                                <form action="{% url 'projects_directory' %}" method="post"
                                      class="modal-dialog modal-drawer-right" role="document">
                                    {% csrf_token %}
                                    <!-- .modal-content -->
                                    <div class="modal-content">
                                        <!-- .modal-header -->
                                        <div class="modal-header">
                                            <h5 id="newProjectLabel" class="modal-title"> Create new project </h5>
                                        </div><!-- /.modal-header -->
                                        <!-- .modal-body -->
                                        <div class="modal-body">
                                            <div class="form-group">
                                                <label for="{{ form.name.id_for_field }}">{{ form.name.label }}</label>
                                                {{ form.name }}
                                                <span>{{ form.name.errors }}</span>
                                            </div>
                                            <div class="form-group">
                                                <label for="{{ form.lead.id_for_field }}">{{ form.lead.label }}</label>
                                                {{ form.lead }}
                                                <span>{{ form.lead.errors }}</span>
                                            </div>
                                            <div class="form-group">
                                                <label for="{{ form.description.id_for_field }}">{{ form.description.label }}</label>
                                                {{ form.description }}
                                                <span>{{ form.description.errors }}</span>
                                            </div>
                                        </div><!-- /.modal-body -->
                                        <!-- .modal-footer -->
                                        <div class="modal-footer">
                                            <button type="button" class="btn btn-warning" data-dismiss="modal">Close
                                            </button>
                                            <button type="submit" class="btn btn-primary">Save</button>
                                        </div><!-- /.modal-footer -->
                                    </div><!-- /.modal-content -->
                                </form><!-- /.modal-dialog -->
                            </div><!-- /.modal -->
                            <!-- /Modal Drawer Right -->
                        {% endif %}


                        <button type="button" class="btn btn-light d-none">
                            <i class="oi oi-data-transfer-upload"></i>
                            <span class="ml-1">Import</span>
                        </button>
                    </div><!-- /.btn-toolbar -->
                </div><!-- /title and toolbar -->
            </header><!-- /.page-title-bar -->

            <!-- .page-section -->
            <div class="page-section">

                <!-- .card -->
                <div class="card card-fluid">

                    <!-- .card-body -->
                    <div class="card-body">

                        <!-- .table-responsive -->
                        <div class="table-responsive">
                            <!-- .table -->
                            <table class="table">
                                <!-- thead -->
                                <thead>
                                <tr>
                                    <th style="min-width:320px">Name</th>
                                    <th> Lead</th>
                                    <th> Created On</th>
                                    <th style="width:100px; min-width:100px;"> &nbsp;</th>
                                </tr>
                                </thead><!-- /thead -->
                                <!-- tbody -->
                                <tbody>

                                {% if projects %}
                                    {% for project in projects %}
                                        <!-- tr -->
                                        <tr>
                                            <td>
                                                <a href="{% url 'project_overview' project.slug %}"
                                                   class="tile tile-img mr-1">
                                                    <span class="img-fluid">{{ project.name|first|capfirst }}</span>
                                                </a>
                                                <a href="{% url 'project_overview' project.slug %}">{{ project.name }}</a>
                                            </td>
                                            <td class="align-middle">{{ project.lead.first_name }} {{ project.lead.last_name }}</td>
                                            <td class="align-middle">{{ project.created_at|date }}</td>
                                            <td class="align-middle text-right">
                                                {% if perms.engineering.change_project %}
                                                    <a href="{% url 'project_overview' project.slug %}"
                                                       class="btn btn-sm btn-icon btn-secondary"><i
                                                            class="fa fa-pencil-alt"></i> <span
                                                            class="sr-only">Edit</span></a>
                                                {% endif %}
                                                {% if perms.engineering.delete_project %}
                                                    <a
                                                            href="#" class="btn btn-sm btn-icon btn-danger"><i
                                                            class="far fa-trash-alt"></i> <span
                                                            class="sr-only">Remove</span></a>
                                                {% endif %}
                                            </td>
                                        </tr><!-- /tr -->
                                    {% endfor %}
                                {% else %}

                                {% endif %}

                                </tbody><!-- /tbody -->
                            </table><!-- /.table -->
                        </div><!-- /.table-responsive -->

                    </div><!-- /.card-body -->

                </div><!-- /.card -->

            </div><!-- /.page-section -->
        </div><!-- /.page-inner -->
    </div><!-- /.page -->

{% endblock %}


{% block js %}

{% endblock %}